version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080" 
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - GITHUB_TOKEN= # Use environment variables for security and put the token
